name: citelibre-rendezvous-platform
services:

  rendezvous-db:
    container_name: citelibre-rendezvous-db
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MARIADB_USER: "${MYSQL_USER}"
      MARIADB_PASSWORD: "${MYSQL_PASSWORD}"
    healthcheck:
      test: [ "CMD", "mariadb", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "-e", "show databases" ]
    networks:
      - citelibre-network

  init-rendezvous-db:
    container_name: citelibre-rendezvous-init-db
    image: mariadb:10.6
    depends_on:
      rendezvous-db:
        condition: service_healthy
    command: sh -c "sh /init_db.sh"
    environment:
      MYSQL_PWD: $MYSQL_ROOT_PASSWORD
      INIT_DATABASE_HOST: rendezvous-db
      INIT_DATABASE_NAME: $RDV_DATABASE
      INIT_APP_USER: $MYSQL_USER
    volumes:
      - ../../citelibre-common/sql/init_db.sh:/init_db.sh
      - ./sql/00-init.sql:/sql/00-init.sql
      #choose between one the following authentication providers
      #- ./sql/01-auth-database.sql:/sql/01-auth-database.sql
      - ./sql/02-auth-keycloak.sql:/sql/02-auth-keycloak.sql
    networks:
      - citelibre-network

  citelibre-rendezvous:
    container_name: citelibre-rendezvous
    image: citelibre/citelibre-rendezvous:${CITELIBRE_IMAGE_VERSION}
    environment:
      LUTECE_PROD_URL: $LUTECE_PROD_URL
      LUTECE_ADMIN_PROD_URL: $LUTECE_ADMIN_PROD_URL
      LUTECE_BASE_URL: $LUTECE_BASE_URL
      LUTECE_HTTPS_SUPPORT: $LUTECE_HTTPS_SUPPORT
      PORTAL_URL: $PORTAL_URL
      PORTAL_USER: $PORTAL_USER
      PORTAL_PASSWORD: $PORTAL_PASSWORD
      ELASTICDATA_ELASTIC_SERVER_URL: $ELASTICDATA_ELASTIC_SERVER_URL
      ELASTICDATA_ELASTIC_SERVER_LOGIN: $ELASTICDATA_ELASTIC_SERVER_LOGIN
      ELASTICDATA_ELASTIC_SERVER_PWD: $ELASTICDATA_ELASTIC_SERVER_PWD
      MATOMO_DEFAULT_SERVER_HTTP_URL: $MATOMO_DEFAULT_SERVER_HTTP_URL
      MATOMO_DEFAULT_SERVER_HTTPS_URL: $MATOMO_DEFAULT_SERVER_HTTPS_URL
      SOLR_SERVER_ADDRESS: $SOLR_SERVER_ADDRESS
      KIBANA_URL: $KIBANA_URL
      KIBANA_URL_IFRAME: $KIBANA_URL_IFRAME
      ADMINAUTHENTICATIONOAUTH2_SERVER_ISSUER: $ADMINAUTHENTICATIONOAUTH2_SERVER_ISSUER
      ADMINAUTHENTICATIONOAUTH2_SERVER_ENABLEJWTPARSER: $ADMINAUTHENTICATIONOAUTH2_SERVER_ENABLEJWTPARSER
      ADMINAUTHENTICATIONOAUTH2_SERVER_LOGOUTENDPOINTURI: $ADMINAUTHENTICATIONOAUTH2_SERVER_LOGOUTENDPOINTURI
      ADMINAUTHENTICATIONOAUTH2_SERVER_TOKENENDPOINTURI: $ADMINAUTHENTICATIONOAUTH2_SERVER_TOKENENDPOINTURI
      ADMINAUTHENTICATIONOAUTH2_SERVER_AUTHORIZATIONENDPOINTURI: $ADMINAUTHENTICATIONOAUTH2_SERVER_AUTHORIZATIONENDPOINTURI
      ADMINAUTHENTICATIONOAUTH2_AUTHDATACLIENT_DATASERVERURI: $ADMINAUTHENTICATIONOAUTH2_AUTHDATACLIENT_DATASERVERURI
      ADMINAUTHENTICATIONOAUTH2_CLIENT_CLIENTID: $ADMINAUTHENTICATIONOAUTH2_CLIENT_CLIENTID
      ADMINAUTHENTICATIONOAUTH2_CLIENT_CLIENTSECRET: $ADMINAUTHENTICATIONOAUTH2_CLIENT_CLIENTSECRET
      ADMINAUTHENTICATIONOAUTH2_URL_DOLOGOUT: $ADMINAUTHENTICATIONOAUTH2_URL_DOLOGOUT
      ADMINAUTHENTICATIONOAUTH2_URL_LOGIN_PAGE: $ADMINAUTHENTICATIONOAUTH2_URL_LOGIN_PAGE
      LUTECE_ADMIN_LOGOUT_URL: $LUTECE_ADMIN_LOGOUT_URL
      MYLUTECE_URL_DOLOGOUT: $MYLUTECE_URL_DOLOGOUT
      MYLUTECE_OAUTH2_AUTHDATACLIENT_DATASERVERURI: $MYLUTECE_OAUTH2_AUTHDATACLIENT_DATASERVERURI
      MYLUTECE_OAUTH2_SERVER_ISSUER: $MYLUTECE_OAUTH2_SERVER_ISSUER
      MYLUTECE_OAUTH2_SERVER_AUTHORIZATIONENDPOINTURI: $MYLUTECE_OAUTH2_SERVER_AUTHORIZATIONENDPOINTURI
      MYLUTECE_OAUTH2_SERVER_TOKENENDPOINTURI: $MYLUTECE_OAUTH2_SERVER_TOKENENDPOINTURI
      MYLUTECE_OAUTH2_SERVER_LOGOUTENDPOINTURI: $MYLUTECE_OAUTH2_SERVER_LOGOUTENDPOINTURI
      MYLUTECE_OAUTH2_SERVER_ENABLEJWTPARSER: $MYLUTECE_OAUTH2_SERVER_ENABLEJWTPARSER
      MYLUTECE_OAUTH2_CLIENT_CLIENTID: $MYLUTECE_OAUTH2_CLIENT_CLIENTID
      MYLUTECE_OAUTH2_CLIENT_CLIENTSECRET: $MYLUTECE_OAUTH2_CLIENT_CLIENTSECRET
      OAUTH2_SERVER_ISSUER: $OAUTH2_SERVER_ISSUER
      OAUTH2_SERVER_AUTHORIZATIONENDPOINTURI: $OAUTH2_SERVER_AUTHORIZATIONENDPOINTURI
      OAUTH2_SERVER_TOKENENDPOINTURI: $OAUTH2_SERVER_TOKENENDPOINTURI
      OAUTH2_SERVER_LOGOUTENDPOINTURI: $OAUTH2_SERVER_LOGOUTENDPOINTURI
      OAUTH2_SERVER_ENABLEJWTPARSER: $OAUTH2_SERVER_ENABLEJWTPARSER
      OAUTH2_CLIENT_CLIENTID: $OAUTH2_CLIENT_CLIENTID
      OAUTH2_CLIENT_CLIENTSECRET: $OAUTH2_CLIENT_CLIENTSECRET
    depends_on:
      init-rendezvous-db:
        condition: service_completed_successfully
    volumes:
      - ${CITELIBRE_DOCKER_VOLUME_PATH}:/opt/applications/apache-tomcat/webapps/citelibre-rendezvous/WEB-INF/logs
    networks:
      - citelibre-network

networks:
  citelibre-network:
    external: true
