name: citelibre-platform
services:

  mariadb:
    container_name: citelibre-platform-db
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MARIADB_USER: $MYSQL_USER
      MARIADB_PASSWORD: $MYSQL_PASSWORD
    healthcheck:
      test: [ "CMD", "mariadb", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "-e", "show databases" ]
    networks:
      - citelibre-network

  init-matomo-db:
    container_name: citelibre-init-matomo-db
    image: mariadb:10.6
    depends_on:
      mariadb:
        condition: service_healthy
    command: sh -c "sh /init_db.sh"
    environment:
      MYSQL_PWD: $MYSQL_ROOT_PASSWORD
      INIT_DATABASE_HOST: citelibre-platform-db
      INIT_DATABASE_NAME: $MATOMO_DATABASE
    volumes:
      - ./common/sql/init_db.sh:/init_db.sh
      - ./matomo/sql/init.sql:/init.sql
    networks:
      - citelibre-network

  matomo:
    container_name: citelibre-matomo
    image: matomo:5.0.3
    depends_on:
      init-matomo-db:
        condition: service_completed_successfully
    environment:
      MATOMO_DATABASE_HOST: $MATOMO_DATABASE_HOST
      MATOMO_DATABASE_ADAPTER: $MATOMO_DATABASE_ADAPTER
      MATOMO_DATABASE_TABLES_PREFIX: $MATOMO_DATABASE_TABLES_PREFIX
      MATOMO_DATABASE_USERNAME: $MYSQL_USER
      MATOMO_DATABASE_PASSWORD: $MYSQL_PASSWORD
      MATOMO_DATABASE_DBNAME: $MATOMO_DATABASE
      MARIADB_AUTO_UPGRADE: $MARIADB_AUTO_UPGRADE
      MARIADB_INITDB_SKIP_TZINFO: $MARIADB_INITDB_SKIP_TZINFO
    ports:
      - "8484:80"
    networks:
      - citelibre-network

  #https://github.com/docker-solr/docker-solr-examples/tree/master/custom-configset
  solr:
    container_name: citelibre-solr
    user: solr
    image: solr:9.1.1
    mem_limit: 1g
    command:
      - solr-precreate
      - citelibre
      - /opt/solr/server/solr/configsets/myconfig
    ports:
      - "8983:8983"
    volumes:
      - ./solr/citelibre:/opt/solr/server/solr/configsets/myconfig:ro
    networks:
      - citelibre-network

  elasticsearch:
    container_name: citelibre-elastic
    image: elasticsearch:8.18.4
    environment:
      bootstrap.memory_lock: true
      cluster.name: "citelibre-elasticsearch"
      network.host: 0.0.0.0
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      ELASTICSEARCH_USERNAME: $ELASTICSEARCH_USERNAME
      ELASTICSEARCH_PASSWORD: $ELASTICSEARCH_PASSWORD
      ES_JAVA_OPTS: -Xms750m -Xmx750m
    healthcheck:
      test: curl -s http://citelibre-elastic:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 120
    ports:
      - "9200:9200"
    networks:
      - citelibre-network

  kibana:
    container_name: citelibre-kibana
    image: kibana:8.18.4
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_USERNAME: $ELASTICSEARCH_USERNAME
      ELASTICSEARCH_PASSWORD: $ELASTICSEARCH_PASSWORD
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    volumes:
      - ./kibana/init.sh:/tmp/init.sh
      - ./kibana/export.ndjson:/tmp/export.ndjson
    #command: "/bin/sh /tmp/init.sh"
    networks:
      - citelibre-network

networks:
  citelibre-network:
    name: citelibre-network