name: Github CI

on: [push, pull_request]

env:
  MAVEN_OPTS: -Dmaven.repo.local=/home/runner/work/citelibre/citelibre/.m2 -Dmaven.artifact.threads=256 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  build:
    name: Package RendezVous
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/work/citelibre/citelibre/.m2
          key: m2_repository
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build
        run: mvn package -Passembly,rendezvous -Dm2.location=/home/runner/work/citelibre/citelibre/.m2
      - name: Remove Snapshots Before Caching
        run: find /home/runner/work/citelibre/citelibre/.m2 -name '*SNAPSHOT' | xargs rm -Rf
