name: Github CI

on: [push, pull_request]

env:
  JAVA_VERSION: '21'
  MAVEN_VERSION: '3.6.3'

jobs:
  build:
    name: Package RendezVous
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v7

      # ---------------------------------------------------------
      # Setup Java
      # ---------------------------------------------------------
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven

      # ---------------------------------------------------------
      # Setup Maven
      # ---------------------------------------------------------
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5.1
        with:
          maven-version: ${{ env.MAVEN_VERSION }}

      # ---------------------------------------------------------
      # Build
      # ---------------------------------------------------------
      - name: Build
        run: mvn package -Passembly,rendezvous
